name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Connected to EC2 instance."
            if [ -d ~/pipeline-test ]; then
              echo "Repository exists. Pulling latest changes..."
              cd ~/pipeline-test
              git reset --hard
              git pull origin main
            else
              echo "Repository not found. Cloning repository..."
              git clone https://github.com/muhammadbilal345/pipeline-test.git ~/pipeline-test
            fi
            echo "Code deployment complete."
