name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          host: ec2-18-212-102-220.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Connected to EC2 instance."
            mkdir -p ~/test-folder
            echo "Folder 'test-folder' created successfully."
