name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          host: ec2-44-220-162-146.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Connected to EC2 instance."
            git pull origin main
            # Add any commands to start or restart your application here.
