name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Connected to EC2 instance."
            
            # Check if the repository already exists and pull or clone the latest code
            if [ -d ~/pipeline-test ]; then
              echo "Repository exists. Pulling latest changes..."
              cd ~/pipeline-test
              git reset --hard
              git pull origin main
            else
              echo "Repository not found. Cloning repository..."
              git clone https://github.com/muhammadbilal345/pipeline-test.git ~/pipeline-test
            fi
            
            echo "Code deployment complete."            
            
            # Kill any existing instances of the script
            echo "Checking for existing script instances..."
            pkill -f "pipeline-test/python3 app.py" || echo "No existing script instances found."

            echo "Activating venv"
            source venv/bin/activate
            
            # Install required dependencies
            echo "Installing dependencies..."
            if [ -f requirements.txt ]; then
              pip3 install -r requirements.txt
            else
              echo "No requirements.txt file found. Skipping dependency installation."
            fi
            
            # Start the application with nohup and disown
            echo "Starting the application..."
            source venv
            nohup python3 app.py &
            echo "Application started successfully with nohup."
