name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Connected to EC2 instance."
            echo "Pulling latest code..."
            if [ -d .git ]; then
              git reset --hard
              git pull origin main
            else
              git clone https://github.com/muhammadbilal345/pipeline-test.git .
            fi
            echo "Latest code pulled successfully."
